name: Build and Test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: 'Build and Test (Node: ${{ matrix.node.name }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - name: LTS
            version: lts/*
          - name: Previous LTS
            version: lts/-1
          - name: Current
            version: node
    steps:
      - name: Check out the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node.version }}
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_FUND: '0'
          NPM_CONFIG_AUDIT: '0'
          SUPPRESS_SUPPORT: '1'
          NO_UPDATE_NOTIFIER: 'true'

      - name: Run postinstall scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Run tests
        run: npm test

  dogfood:
    name: Dogfooding
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node.version }}
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_FUND: '0'
          NPM_CONFIG_AUDIT: '0'
          SUPPRESS_SUPPORT: '1'
          NO_UPDATE_NOTIFIER: 'true'

      - name: Run postinstall scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Build
        run: npm run build

      - name: Run tests
        run: |
          npx tsx --test-reporter=./dist/lib/index.mjs --test-reporter-destination=stdout --test-reporter=spec --test-reporter-destination=stdout --test test/*/*.spec.mts
