name: Failing Workflow

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fail:
    name: Fail tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: |
          node --test-reporter=./dist/lib/index.mjs --test-reporter-destination=stdout --test-reporter=spec --test-reporter-destination=stdout --test test/integration/fail.spec.mjs
