name: Liniting

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NPM_CONFIG_FUND: '0'
          NPM_CONFIG_AUDIT: '0'
          SUPPRESS_SUPPORT: '1'
          NO_UPDATE_NOTIFIER: 'true'

      - name: Run ESLint
        run: npm run lint

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NPM_CONFIG_FUND: '0'
          NPM_CONFIG_AUDIT: '0'
          SUPPRESS_SUPPORT: '1'
          NO_UPDATE_NOTIFIER: 'true'

      - name: Run tsc
        run: npm run typecheck
